# gohatch template configuration
# https://github.com/oliverandrich/gohatch

version = 1

# File extensions for module path and variable replacement
# (in addition to .go files which are always processed)
extensions = ["templ", "md"]
